### ISSUE TITLE
 TypeError: cannot unpack non-iterable Parameters object

### ISSUE THREAD

**Issue by Linardos** [adap/flower#1350]
### Describe the bug

Trying to make a minimal reproducible example to store PyTorch checkpoints. I use 3 scripts: cifar.py, client.py and server.py as described in https://flower.dev/docs/example-pytorch-from-centralized-to-federated.html

I am amending the server.py script to include a checkpoint strategy as outlined in " Steps/Code to Reproduce "
However, the following error pops up during the storing. It seems to be something at a low-level of the library so not sure how to handle it:

```
Saving round 1 aggregated_parameters...
Traceback (most recent call last):
  File "server_checkpointing.py", line 39, in <module>
    fl.server.start_server("0.0.0.0:8080",
  File "/home/linardos/.local/lib/python3.8/site-packages/flwr/server/app.py", line 83, in start_server
    _fl(
  File "/home/linardos/.local/lib/python3.8/site-packages/flwr/server/app.py", line 118, in _fl
    hist = server.fit(num_rounds=config["num_rounds"])
  File "/home/linardos/.local/lib/python3.8/site-packages/flwr/server/server.py", line 138, in fit
    res_fit = self.fit_round(rnd=current_round)
  File "/home/linardos/.local/lib/python3.8/site-packages/flwr/server/server.py", line 283, in fit_round
    parameters_aggregated, metrics_aggregated = aggregated_result
TypeError: cannot unpack non-iterable Parameters object

```

### Steps/Code to Reproduce

```
import flwr as fl
from typing import List, Optional, Tuple
import cifar
import torch
from collections import OrderedDict

DEVICE: str = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
# Load PyTorch model
net = cifar.Net().to(DEVICE) 
class SaveModelStrategy(fl.server.strategy.FedAvg):
    def aggregate_fit(
        self,
        rnd: int,
        results: List[Tuple[fl.server.client_proxy.ClientProxy, fl.common.FitRes]],
        failures: List[BaseException],
    ) -> Optional[fl.common.Weights]:

        """Aggregate model weights using weighted average and store checkpoint"""
        aggregated_parameters_tuple = super().aggregate_fit(rnd, results, failures)
        aggregated_parameters, _ = aggregated_parameters_tuple
        # log_dict['aggregated_parameters']=aggregated_parameters
    
        if aggregated_parameters is not None:
            print(f"Saving round {rnd} aggregated_parameters...")
            # Convert `Parameters` to `List[np.ndarray]`
            aggregated_weights: List[np.ndarray] = fl.common.parameters_to_weights(aggregated_parameters)
            
            # Convert `List[np.ndarray]` to PyTorch`state_dict`
            params_dict = zip(net.state_dict().keys(), aggregated_weights)
            state_dict = OrderedDict({k: torch.tensor(v) for k, v in params_dict})
            net.load_state_dict(state_dict, strict=True)
            # Save the model
            torch.save(net.state_dict(), f"model_round_{rnd}.pth")

        return aggregated_parameters

if __name__ == "__main__":
    fl.server.start_server("0.0.0.0:8080", 
    strategy=SaveModelStrategy(),
    config={"num_rounds":3})

```

### Expected Results

The training to proceed normally with checkpoints stored

### Actual Results

```
Saving round 1 aggregated_parameters...
Traceback (most recent call last):
  File "server_checkpointing.py", line 39, in <module>
    fl.server.start_server("0.0.0.0:8080",
  File "/home/linardos/.local/lib/python3.8/site-packages/flwr/server/app.py", line 83, in start_server
    _fl(
  File "/home/linardos/.local/lib/python3.8/site-packages/flwr/server/app.py", line 118, in _fl
    hist = server.fit(num_rounds=config["num_rounds"])
  File "/home/linardos/.local/lib/python3.8/site-packages/flwr/server/server.py", line 138, in fit
    res_fit = self.fit_round(rnd=current_round)
  File "/home/linardos/.local/lib/python3.8/site-packages/flwr/server/server.py", line 283, in fit_round
    parameters_aggregated, metrics_aggregated = aggregated_result
TypeError: cannot unpack non-iterable Parameters object

```

**Comment by pedropgusmao** [comment]
Hi @Linardos. The server.py in line283 is expecting `aggrgated_result` to be a tuple made of (`Parameters`, `Metrics`) as seen in https://flower.dev/docs/apiref-flwr.html?highlight=fedavg#flwr.server.strategy.FedAvg.aggregate_fit . However, your implementation is only returning the `Parameters`. A quick fix would be to return a `aggregated_parameters, {}` if you don't need the `metrics_aggregated`
