### ISSUE TITLE
Error when running remote but not when running local

### ISSUE THREAD

**Issue by Linardos** [adap/flower#1368]
### Describe the bug

There's this error during the aggregation step that appears only when I run my sever - client scripts with remote connections. If I run the server and clients on a single machine it doesn't occur and training proceeds normally. It seems to be a low-level error at the aggregate module. It has happened once before and vanished without me realizing how it came or how it vanished in the first place.

### Steps/Code to Reproduce

Not sure I can reproduce it in a minimal code example. I'm using dockerized clients and the server runs on another computer. I'm looking to see if the error is familiar for now. 

### Expected Results

Training to proceed normally.

### Actual Results
```
Using cache found in /home/user/.cache/torch/hub/pytorch_vision_v0.10.0
INFO flower 2022-08-10 11:43:26,388 | app.py:77 | Flower server running (insecure, 120 rounds)
INFO flower 2022-08-10 11:43:26,388 | server.py:118 | Initializing global parameters
INFO flower 2022-08-10 11:43:26,388 | server.py:304 | Requesting initial parameters from one random client
Using cache found in /home/user/.cache/torch/hub/pytorch_vision_v0.10.0
INFO flower 2022-08-10 12:32:30,505 | app.py:77 | Flower server running (insecure, 120 rounds)
INFO flower 2022-08-10 12:32:30,566 | server.py:118 | Initializing global parameters
INFO flower 2022-08-10 12:32:30,566 | server.py:304 | Requesting initial parameters from one random client
INFO flower 2022-08-10 12:32:53,809 | server.py:307 | Received initial parameters from one random client
INFO flower 2022-08-10 12:32:53,811 | server.py:120 | Evaluating initial parameters
INFO flower 2022-08-10 12:32:53,811 | server.py:133 | FL starting
DEBUG flower 2022-08-10 12:32:57,933 | server.py:251 | fit_round: strategy sampled 2 clients (out of 2)
DEBUG flower 2022-08-10 12:33:54,305 | server.py:260 | fit_round received 2 results and 0 failures
Using cache found in /home/user/.cache/torch/hub/pytorch_vision_v0.10.0
WARNING flower 2022-08-10 12:33:55,135 | aggregator.py:338 | No fit_metrics_aggregation_fn provided
DEBUG flower 2022-08-10 12:33:55,393 | server.py:201 | evaluate_round: strategy sampled 2 clients (out of 2)
DEBUG flower 2022-08-10 12:34:39,459 | server.py:210 | evaluate_round received 2 results and 0 failures
Generating experiment 0064_TRIAL_Averaging
Length results is 2
{'accuracies_aggregated': [], 'total_val_loss': [], 'time_spent': []}
Saving round 1 aggregated_parameters...
[0.4, 0.4]
Round 1 accuracy aggregated from client results: 0.4
Traceback (most recent call last):
 File "server.py", line 298, in <module>
  fl.server.start_server(strategy=strategy, server_address=f"[::]:{CONFIG['port']}", config={"num_rounds": CONFIG['hyperparameters']['federated_rounds']})
 File "/home/user/BFP/fl_env/lib/python3.8/site-packages/flwr/server/app.py", line 83, in start_server
  _fl(
 File "/home/user/BFP/fl_env/lib/python3.8/site-packages/flwr/server/app.py", line 118, in _fl
  hist = server.fit(num_rounds=config["num_rounds"])
 File "/home/user/BFP/fl_env/lib/python3.8/site-packages/flwr/server/server.py", line 160, in fit
  res_fed = self.evaluate_round(rnd=current_round)
 File "/home/user/BFP/fl_env/lib/python3.8/site-packages/flwr/server/server.py", line 221, in evaluate_round
  ] = self.strategy.aggregate_evaluate(rnd, results, failures)
 File "server.py", line 239, in aggregate_evaluate
  return super().aggregate_evaluate(rnd, results, failures)
 File "/home/user/BFP/src/aggregator.py", line 356, in aggregate_evaluate
  loss_aggregated = weighted_loss_avg(
 File "/home/user/BFP/fl_env/lib/python3.8/site-packages/flwr/server/strategy/aggregate.py", line 47, in weighted_loss_avg
  [num_examples for num_examples, _, _ in results]
 File "/home/user/BFP/fl_env/lib/python3.8/site-packages/flwr/server/strategy/aggregate.py", line 47, in <listcomp>
  [num_examples for num_examples, _, _ in results]
ValueError: not enough values to unpack (expected 3, got 2)
```

**Comment by danieljanes** [comment]
Thanks for the report @Linardos , does this also happen with Flower 1.0?

**Comment by shashankc28** [comment]
Hi Linardos, can you please provide a sample of your code you are using to create connection between 2 machines . i am also using a dockerized solution but not able to create connection . is there a list of ports i need to expose ?
thanks in advance :)

**Comment by WilliamLindskog** [comment]
Hi
thanks for raising this. I am closing this issue as flwr can be run in deployment, here's an example: https://github.com/adap/flower/tree/main/examples/app-pytorch
