### ISSUE TITLE
Quickstart mlcube fails on setup script

### ISSUE THREAD

**Issue by adam-narozniak** [adap/flower#1571]
### Describe the bug
After moving to the new flwr version by`python = ">=3.7,<3.11"` in pyproject.toml and changing `weights_to_parameters` to `ndarrays_to_parameters` in mlcube_utils.py other issue arises (not checked on the legacy 0.17 version)

Log when running `./dev/setup.sh`
```text
Cleanup mlcube and clients directory
Clone mlcube from GitHub
Cloning into 'mlcube_examples'...
remote: Enumerating objects: 998, done.
remote: Counting objects: 100% (181/181), done.
remote: Compressing objects: 100% (136/136), done.
remote: Total 998 (delta 77), reused 71 (delta 37), pack-reused 817
Receiving objects: 100% (998/998), 665.80 KiB | 5.41 MiB/s, done.
Resolving deltas: 100% (496/496), done.
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
2023-01-13 13:38:27 adams-macbook-pro.home mlcube.shell[66685] ERROR Command = 'docker build  -t mlcommons/mnist_fl_tensorflow:0.0.1 -f /Users/adamnarozniak/Desktop/testing-flwr/quickstart_mlcube/mlcube/build/Dockerfile /Users/adamnarozniak/Desktop/testing-flwr/quickstart_mlcube/mlcube/build', return_code = 256, die_on_error = True
Traceback (most recent call last):
  File "/Users/adamnarozniak/.pyenv/versions/flwr-1.2-testing-p3.8/bin/mlcube", line 8, in <module>
    sys.exit(cli())
  File "/Users/adamnarozniak/.pyenv/versions/3.8/envs/flwr-1.2-testing-p3.8/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/adamnarozniak/.pyenv/versions/3.8/envs/flwr-1.2-testing-p3.8/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/adamnarozniak/.pyenv/versions/3.8/envs/flwr-1.2-testing-p3.8/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/adamnarozniak/.pyenv/versions/3.8/envs/flwr-1.2-testing-p3.8/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/adamnarozniak/.pyenv/versions/3.8/envs/flwr-1.2-testing-p3.8/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/adamnarozniak/.pyenv/versions/3.8/envs/flwr-1.2-testing-p3.8/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/adamnarozniak/.pyenv/versions/3.8/envs/flwr-1.2-testing-p3.8/lib/python3.8/site-packages/mlcube/__main__.py", line 153, in configure
    docker_runner.configure()
  File "/Users/adamnarozniak/.pyenv/versions/3.8/envs/flwr-1.2-testing-p3.8/lib/python3.8/site-packages/mlcube_docker/docker_run.py", line 107, in configure
    Shell.run(docker, 'build', build_args, '-t', image, '-f', recipe, context)
  File "/Users/adamnarozniak/.pyenv/versions/3.8/envs/flwr-1.2-testing-p3.8/lib/python3.8/site-packages/mlcube/shell.py", line 33, in run
    raise RuntimeError("Command failed: {}".format(cmd))
RuntimeError: Command failed: docker build  -t mlcommons/mnist_fl_tensorflow:0.0.1 -f /Users/adamnarozniak/Desktop/testing-flwr/quickstart_mlcube/mlcube/build/Dockerfile /Users/adamnarozniak/Desktop/testing-flwr/quickstart_mlcube/mlcube/build
```

### Steps/Code to Reproduce

Follow the instructions at https://github.com/adap/flower/tree/main/examples/quickstart_mlcube till `./dev/setup.sh`

### Expected Results

Running the example without errors.

### Actual Results

Error occurs.

**Comment by charlesbvll** [comment]
The error is happening because the `Docker` deamon is not running. 
On MacOS, depending on how you installed `Docker`, you can just open the `Docker Desktop` app to launch the deamon. 
On Linux you can just run `sudo systemctl start docker` (if your service manager is `systemd`).

And also if `Docker` is only setup for the root user, you might have to run the setup script as sudo: `sudo ./dev/setup.sh`.

I ran it without issues on my machine, so I will close this issue.
