### ISSUE TITLE
Deserialization Error: Python 3.8, Flower 1.3, Ray 1.13

### ISSUE THREAD

**Issue by kjam** [adap/flower#1688]
### Describe the bug

When I use a PyTorch Vision example and run it on my computer, I immediately receive a Deserialization error. When asking in your Slack channel, other folks with Python 3.10 on a different operating system (windows instead of linux), do not receive the error. 

I also receive this error (slightly different flavor, because the Python version differences) when using the same versions of Flower and Ray using a Python 3.9 environment on MacOS. 

This is somewhat of a pressing issue, as I recommend this library for use in an upcoming book. I am happy to help debug further, should you need extra information or help.

### Steps/Code to Reproduce

https://github.com/kjam/practical-data-privacy/blob/main/10%20-%20Federated%20Learning%20with%20flwr.ipynb

### Expected Results

The code will run to train the model

### Actual Results

```
INFO flwr 2023-02-19 18:22:24,536 | app.py:145 | Starting Flower simulation, config: ServerConfig(num_rounds=100, round_timeout=None)
INFO flwr 2023-02-19 18:22:26,646 | app.py:179 | Flower VCE: Ray initialized with resources: {'memory': 5845494990.0, 'node:192.168.1.171': 1.0, 'object_store_memory': 2922747494.0, 'CPU': 8.0}
INFO flwr 2023-02-19 18:22:26,648 | server.py:86 | Initializing global parameters
INFO flwr 2023-02-19 18:22:26,649 | server.py:270 | Requesting initial parameters from one random client
2023-02-19 18:22:27,359	ERROR serialization.py:342 -- 
Traceback (most recent call last):
  File "/home/katharine/.virtualenvs/py3data/lib/python3.8/site-packages/ray/serialization.py", line 201, in _deserialize_msgpack_data
    obj = MessagePackSerializer.loads(msgpack_data, _python_deserializer)
  File "python/ray/includes/serialization.pxi", line 191, in ray._raylet.MessagePackSerializer.loads
  File "python/ray/includes/serialization.pxi", line 192, in ray._raylet.MessagePackSerializer.loads
  File "msgpack/_unpacker.pyx", line 161, in msgpack._unpacker.unpackb
TypeError: unpackb() got an unexpected keyword argument 'strict_map_key'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/katharine/.virtualenvs/py3data/lib/python3.8/site-packages/ray/serialization.py", line 340, in deserialize_objects
    obj = self._deserialize_object(data, metadata, object_ref)
  File "/home/katharine/.virtualenvs/py3data/lib/python3.8/site-packages/ray/serialization.py", line 259, in _deserialize_object
    obj = self._deserialize_msgpack_data(data, metadata_fields)
  File "/home/katharine/.virtualenvs/py3data/lib/python3.8/site-packages/ray/serialization.py", line 203, in _deserialize_msgpack_data
    raise DeserializationError()
ray.serialization.DeserializationError
DEBUG flwr 2023-02-19 18:22:27,361 | ray_client_proxy.py:72 | System error: 
traceback: Traceback (most recent call last):
  File "/home/katharine/.virtualenvs/py3data/lib/python3.8/site-packages/ray/serialization.py", line 201, in _deserialize_msgpack_data
    obj = MessagePackSerializer.loads(msgpack_data, _python_deserializer)
  File "python/ray/includes/serialization.pxi", line 191, in ray._raylet.MessagePackSerializer.loads
  File "python/ray/includes/serialization.pxi", line 192, in ray._raylet.MessagePackSerializer.loads
  File "msgpack/_unpacker.pyx", line 161, in msgpack._unpacker.unpackb
TypeError: unpackb() got an unexpected keyword argument 'strict_map_key'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/katharine/.virtualenvs/py3data/lib/python3.8/site-packages/ray/serialization.py", line 340, in deserialize_objects
    obj = self._deserialize_object(data, metadata, object_ref)
  File "/home/katharine/.virtualenvs/py3data/lib/python3.8/site-packages/ray/serialization.py", line 259, in _deserialize_object
    obj = self._deserialize_msgpack_data(data, metadata_fields)
  File "/home/katharine/.virtualenvs/py3data/lib/python3.8/site-packages/ray/serialization.py", line 203, in _deserialize_msgpack_data
    raise DeserializationError()
ray.serialization.DeserializationError

(launch_and_get_parameters pid=200550) 2023-02-19 18:22:27,356	ERROR serialization.py:342 -- 
(launch_and_get_parameters pid=200550) Traceback (most recent call last):
(launch_and_get_parameters pid=200550)   File "/home/katharine/.virtualenvs/py3data/lib/python3.8/site-packages/ray/serialization.py", line 201, in _deserialize_msgpack_data
(launch_and_get_parameters pid=200550)     obj = MessagePackSerializer.loads(msgpack_data, _python_deserializer)
(launch_and_get_parameters pid=200550)   File "python/ray/includes/serialization.pxi", line 191, in ray._raylet.MessagePackSerializer.loads
(launch_and_get_parameters pid=200550)   File "python/ray/includes/serialization.pxi", line 192, in ray._raylet.MessagePackSerializer.loads
(launch_and_get_parameters pid=200550)   File "msgpack/_unpacker.pyx", line 161, in msgpack._unpacker.unpackb
(launch_and_get_parameters pid=200550) TypeError: unpackb() got an unexpected keyword argument 'strict_map_key'
(launch_and_get_parameters pid=200550) 
(launch_and_get_parameters pid=200550) During handling of the above exception, another exception occurred:
(launch_and_get_parameters pid=200550) 
(launch_and_get_parameters pid=200550) Traceback (most recent call last):
(launch_and_get_parameters pid=200550)   File "/home/katharine/.virtualenvs/py3data/lib/python3.8/site-packages/ray/serialization.py", line 340, in deserialize_objects
(launch_and_get_parameters pid=200550)     obj = self._deserialize_object(data, metadata, object_ref)
(launch_and_get_parameters pid=200550)   File "/home/katharine/.virtualenvs/py3data/lib/python3.8/site-packages/ray/serialization.py", line 237, in _deserialize_object
(launch_and_get_parameters pid=200550)     return self._deserialize_msgpack_data(data, metadata_fields)
(launch_and_get_parameters pid=200550)   File "/home/katharine/.virtualenvs/py3data/lib/python3.8/site-packages/ray/serialization.py", line 203, in _deserialize_msgpack_data
(launch_and_get_parameters pid=200550)     raise DeserializationError()
(launch_and_get_parameters pid=200550) ray.serialization.DeserializationError
(launch_and_get_parameters pid=200550) 2023-02-19 18:22:27,357	ERROR serialization.py:342 -- 
(launch_and_get_parameters pid=200550) Traceback (most recent call last):
(launch_and_get_parameters pid=200550)   File "/home/katharine/.virtualenvs/py3data/lib/python3.8/site-packages/ray/serialization.py", line 201, in _deserialize_msgpack_data
(launch_and_get_parameters pid=200550)     obj = MessagePackSerializer.loads(msgpack_data, _python_deserializer)
(launch_and_get_parameters pid=200550)   File "python/ray/includes/serialization.pxi", line 191, in ray._raylet.MessagePackSerializer.loads
(launch_and_get_parameters pid=200550)   File "python/ray/includes/serialization.pxi", line 192, in ray._raylet.MessagePackSerializer.loads
(launch_and_get_parameters pid=200550)   File "msgpack/_unpacker.pyx", line 161, in msgpack._unpacker.unpackb
(launch_and_get_parameters pid=200550) TypeError: unpackb() got an unexpected keyword argument 'strict_map_key'
(launch_and_get_parameters pid=200550) 
(launch_and_get_parameters pid=200550) During handling of the above exception, another exception occurred:
(launch_and_get_parameters pid=200550) 
(launch_and_get_parameters pid=200550) Traceback (most recent call last):
(launch_and_get_parameters pid=200550)   File "/home/katharine/.virtualenvs/py3data/lib/python3.8/site-packages/ray/serialization.py", line 340, in deserialize_objects
(launch_and_get_parameters pid=200550)     obj = self._deserialize_object(data, metadata, object_ref)
(launch_and_get_parameters pid=200550)   File "/home/katharine/.virtualenvs/py3data/lib/python3.8/site-packages/ray/serialization.py", line 237, in _deserialize_object
(launch_and_get_parameters pid=200550)     return self._deserialize_msgpack_data(data, metadata_fields)
(launch_and_get_parameters pid=200550)   File "/home/katharine/.virtualenvs/py3data/lib/python3.8/site-packages/ray/serialization.py", line 203, in _deserialize_msgpack_data
(launch_and_get_parameters pid=200550)     raise DeserializationError()
(launch_and_get_parameters pid=200550) ray.serialization.DeserializationError
(launch_and_get_parameters pid=200550) 2023-02-19 18:22:27,357	ERROR serialization.py:342 -- 
(launch_and_get_parameters pid=200550) Traceback (most recent call last):
(launch_and_get_parameters pid=200550)   File "/home/katharine/.virtualenvs/py3data/lib/python3.8/site-packages/ray/serialization.py", line 201, in _deserialize_msgpack_data
(launch_and_get_parameters pid=200550)     obj = MessagePackSerializer.loads(msgpack_data, _python_deserializer)
(launch_and_get_parameters pid=200550)   File "python/ray/includes/serialization.pxi", line 191, in ray._raylet.MessagePackSerializer.loads
(launch_and_get_parameters pid=200550)   File "python/ray/includes/serialization.pxi", line 192, in ray._raylet.MessagePackSerializer.loads
(launch_and_get_parameters pid=200550)   File "msgpack/_unpacker.pyx", line 161, in msgpack._unpacker.unpackb
(launch_and_get_parameters pid=200550) TypeError: unpackb() got an unexpected keyword argument 'strict_map_key'
(launch_and_get_parameters pid=200550) 
(launch_and_get_parameters pid=200550) During handling of the above exception, another exception occurred:
(launch_and_get_parameters pid=200550) 
(launch_and_get_parameters pid=200550) Traceback (most recent call last):
(launch_and_get_parameters pid=200550)   File "/home/katharine/.virtualenvs/py3data/lib/python3.8/site-packages/ray/serialization.py", line 340, in deserialize_objects
(launch_and_get_parameters pid=200550)     obj = self._deserialize_object(data, metadata, object_ref)
(launch_and_get_parameters pid=200550)   File "/home/katharine/.virtualenvs/py3data/lib/python3.8/site-packages/ray/serialization.py", line 237, in _deserialize_object
(launch_and_get_parameters pid=200550)     return self._deserialize_msgpack_data(data, metadata_fields)
(launch_and_get_parameters pid=200550)   File "/home/katharine/.virtualenvs/py3data/lib/python3.8/site-packages/ray/serialization.py", line 203, in _deserialize_msgpack_data
(launch_and_get_parameters pid=200550)     raise DeserializationError()
(launch_and_get_parameters pid=200550) ray.serialization.DeserializationError

---------------------------------------------------------------------------
RaySystemError                            Traceback (most recent call last)
<ipython-input-8-22fc8e72552f> in <module>
     17 
     18 # start simulation
---> 19 fl.simulation.start_simulation(
     20     client_fn=client_fn,
     21     num_clients=pool_size,

~/.virtualenvs/py3data/lib/python3.8/site-packages/flwr/simulation/app.py in start_simulation(client_fn, num_clients, clients_ids, client_resources, server, config, strategy, client_manager, ray_init_args, keep_initialised)
    194 
    195     # Start training
--> 196     hist = _fl(
    197         server=initialized_server,
    198         config=initialized_config,

~/.virtualenvs/py3data/lib/python3.8/site-packages/flwr/server/app.py in _fl(server, config)
    199 ) -> History:
    200     # Fit model
--> 201     hist = server.fit(num_rounds=config.num_rounds, timeout=config.round_timeout)
    202     log(INFO, "app_fit: losses_distributed %s", str(hist.losses_distributed))
    203     log(INFO, "app_fit: metrics_distributed %s", str(hist.metrics_distributed))

~/.virtualenvs/py3data/lib/python3.8/site-packages/flwr/server/server.py in fit(self, num_rounds, timeout)
     85         # Initialize parameters
     86         log(INFO, "Initializing global parameters")
---> 87         self.parameters = self._get_initial_parameters(timeout=timeout)
     88         log(INFO, "Evaluating initial parameters")
     89         res = self.strategy.evaluate(0, parameters=self.parameters)

~/.virtualenvs/py3data/lib/python3.8/site-packages/flwr/server/server.py in _get_initial_parameters(self, timeout)
    271         random_client = self._client_manager.sample(1)[0]
    272         ins = GetParametersIns(config={})
--> 273         get_parameters_res = random_client.get_parameters(ins=ins, timeout=timeout)
    274         log(INFO, "Received initial parameters from one random client")
    275         return get_parameters_res.parameters

~/.virtualenvs/py3data/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py in get_parameters(self, ins, timeout)
     71         except Exception as ex:
     72             log(DEBUG, ex)
---> 73             raise ex
     74         return cast(
     75             common.GetParametersRes,

~/.virtualenvs/py3data/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py in get_parameters(self, ins, timeout)
     68         ).remote(self.client_fn, self.cid, ins)
     69         try:
---> 70             res = ray.get(future_paramseters_res, timeout=timeout)  # type: ignore
     71         except Exception as ex:
     72             log(DEBUG, ex)

~/.virtualenvs/py3data/lib/python3.8/site-packages/ray/_private/client_mode_hook.py in wrapper(*args, **kwargs)
    103             if func.__name__ != "init" or is_client_mode_enabled_by_default:
    104                 return getattr(ray, func.__name__)(*args, **kwargs)
--> 105         return func(*args, **kwargs)
    106 
    107     return wrapper

~/.virtualenvs/py3data/lib/python3.8/site-packages/ray/worker.py in get(object_refs, timeout)
   1831                     raise value.as_instanceof_cause()
   1832                 else:
-> 1833                     raise value
   1834 
   1835         if is_individual_id:

RaySystemError: System error: 
traceback: Traceback (most recent call last):
  File "/home/katharine/.virtualenvs/py3data/lib/python3.8/site-packages/ray/serialization.py", line 201, in _deserialize_msgpack_data
    obj = MessagePackSerializer.loads(msgpack_data, _python_deserializer)
  File "python/ray/includes/serialization.pxi", line 191, in ray._raylet.MessagePackSerializer.loads
  File "python/ray/includes/serialization.pxi", line 192, in ray._raylet.MessagePackSerializer.loads
  File "msgpack/_unpacker.pyx", line 161, in msgpack._unpacker.unpackb
TypeError: unpackb() got an unexpected keyword argument 'strict_map_key'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/katharine/.virtualenvs/py3data/lib/python3.8/site-packages/ray/serialization.py", line 340, in deserialize_objects
    obj = self._deserialize_object(data, metadata, object_ref)
  File "/home/katharine/.virtualenvs/py3data/lib/python3.8/site-packages/ray/serialization.py", line 259, in _deserialize_object
    obj = self._deserialize_msgpack_data(data, metadata_fields)
  File "/home/katharine/.virtualenvs/py3data/lib/python3.8/site-packages/ray/serialization.py", line 203, in _deserialize_msgpack_data
    raise DeserializationError()
ray.serialization.DeserializationError
```

**Comment by kjam** [comment]
I was able to fix this on my MacOS installation following this advice: https://stackoverflow.com/questions/52345387/python-spacy-typeerror-unpackb-got-an-unexpected-keyword-argument-raw

I haven't yet checked msgpack version on my Linux machine, but will report back when I do.

**Comment by WilliamLindskog** [comment]
Hi @kjam,

is this an issue that you are still experiencing?
