### ISSUE TITLE
Unspecified gRPC keep alive time can lead to errors

### ISSUE THREAD

**Issue by lbhm** [adap/flower#1940]
### Describe the bug

I recently started using a new server for some experiments with Flower and noticed that sometimes, I would receive gRPC errors during training (see below). I am no gRPC expert but as far as I could understand the error message together with some SO posts [[1](https://stackoverflow.com/questions/66271810/grpc-error-on-long-connections-too-many-pings), [2](https://stackoverflow.com/questions/65976781/error-too-many-pings-error-in-grpc-service-calls)], it seems like clients are sometimes sending too many keep alive messages to the server, which causes them to be excluded from training.

The [gRPC configuration](https://github.com/adap/flower/blob/main/src/py/flwr/common/grpc.py#L36-L39) in `flower.common` does not specify the keep alive time but the `grpc` package [generally allows to do so](https://github.com/grpc/grpc/blob/v1.43.x/include/grpc/impl/codegen/grpc_types.h#L237-L239). Therefore, I would like to ask if you think that defining a (reasonably high) keep alive time in `flwr.common` would make sense in your opinion.

### Steps/Code to Reproduce

I used the [Quickstart PyTorch](https://flower.dev/docs/quickstart-pytorch.html) example on a server in our group.

### Expected Results

The training process should complete with no errors.

### Actual Results

In some runs, one or multiple clients drop out of the training because they send too many keep alive call to the server and are subsequently excluded from the training.

```
Traceback (most recent call last):
  File "<project>/flower_sim/client.py", line 117, in <module>
    fl.client.start_numpy_client(
  File "<project>/venv/lib/python3.10/site-packages/flwr/client/app.py", line 252, in start_numpy_client
    start_client(
  File "<project>/venv/lib/python3.10/site-packages/flwr/client/app.py", line 174, in start_client
    server_message = receive()
  File "<project>/venv/lib/python3.10/site-packages/flwr/client/grpc_client/connection.py", line 105, in <lambda>
    receive: Callable[[], ServerMessage] = lambda: next(server_message_iterator)
  File "<project>/venv/lib/python3.10/site-packages/grpc/_channel.py", line 475, in __next__
    return self._next()
  File "<project>/venv/lib/python3.10/site-packages/grpc/_channel.py", line 864, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "Too many pings"
        debug_error_string = "UNKNOWN:Error received from peer ipv4:127.0.0.1:8080 {grpc_message:"Too many pings", grpc_status:14, created_time:"2023-06-16T14:21:10.71384479+02:00"}"
```

**Comment by lbhm** [comment]
Possibly linked to and solved by #2197.

**Comment by WilliamLindskog** [comment]
Hi again, 

After checking, this seems to have been resolved by PRs and new version of flwr. 

Will close this issue for now.
