### ISSUE TITLE
Update the installing dependencies for MAC user

### ISSUE THREAD

**Issue by lusnig** [adap/flower#2113]
### Describe the type of feature and its functionality.

The [installing dependencies ](https://flower.dev/docs/tutorial/Flower-1-Intro-to-FL-PyTorch.html#Installing-dependencies) paragraph of the tutorial are not working under MAC.

I did the following:

1. created a conda env with python 3.10 ( I have the same error with 3.9)
2. 1. installed flower and its dependencies as described in the [tutorial](https://flower.dev/docs/tutorial/Flower-1-Intro-to-FL-PyTorch.html)
3. run python and just import flwr

I got the following error:
`>>> import flwr
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/miniconda3/envs/flower/lib/python3.10/site-packages/flwr/__init__.py", line 18, in <module>
    from flwr.common.version import package_version as _package_version
  File "/Users/miniconda3/envs/flower/lib/python3.10/site-packages/flwr/common/__init__.py", line 19, in <module>
    from .grpc import GRPC_MAX_MESSAGE_LENGTH
  File "/Users/miniconda3/envs/flower/lib/python3.10/site-packages/flwr/common/grpc.py", line 21, in <module>
    import grpc
  File "/Users/miniconda3/envs/flower/lib/python3.10/site-packages/grpc/__init__.py", line 22, in <module>
    from grpc import _compression
  File "/Users/miniconda3/envs/flower/lib/python3.10/site-packages/grpc/_compression.py", line 15, in <module>
    from grpc._cython import cygrpc
ImportError: dlopen(/Users/miniconda3/envs/flower/lib/python3.10/site-packages/grpc/_cython/cygrpc.cpython-310-darwin.so, 0x0002): symbol not found in flat namespace '_CFRelease'`

### Describe step by step what files and adjustments are you planning to include.

The proposed and working solution (thx to Javier) is the following.

1. Install as described in the tutorial
2. uninstall and re install the `grpcio` lib

I only tried this solution into a conda environment,  the steps are the following:

- pip uninstall grpcio
- conda install grpcio

**Comment by WilliamLindskog** [comment]
Hi 

Thanks for raising this. I tried this on MAC and it seems to have been resolved through new version of flwr. Thus, I will close this for now.
