### ISSUE TITLE
Client-Server not connecting via Docker

### ISSUE THREAD

**Issue by Barathwaja** [adap/flower#2282]
I'm trying to use two dockers containers - one `client` and other `server` in one machine it still throws the below error. I changed `0.0.0.0 or localhost or 127.0.0.1` everything but client fails. Please assist.

```
INFO flwr 2023-09-02 04:35:38,311 | grpc.py:49 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2023-09-02 04:35:38,314 | connection.py:42 | ChannelConnectivity.IDLE
DEBUG flwr 2023-09-02 04:35:38,318 | connection.py:42 | ChannelConnectivity.CONNECTING
DEBUG flwr 2023-09-02 04:35:38,403 | connection.py:42 | ChannelConnectivity.TRANSIENT_FAILURE
DEBUG flwr 2023-09-02 04:35:38,606 | connection.py:139 | gRPC channel closed
Traceback (most recent call last):
  File "client.py", line 163, in <module>
    client=FlightClient())
  File "/usr/local/lib/python3.7/dist-packages/flwr/client/app.py", line 294, in start_numpy_client
    transport=transport,
  File "/usr/local/lib/python3.7/dist-packages/flwr/client/app.py", line 201, in start_client
    task_ins = receive()
  File "/usr/local/lib/python3.7/dist-packages/flwr/client/grpc_client/connection.py", line 116, in receive
    server_message = next(server_message_iterator)
  File "/usr/local/lib/python3.7/dist-packages/grpc/_channel.py", line 541, in _next_
    return self._next()
  File "/usr/local/lib/python3.7/dist-packages/grpc/_channel.py", line 950, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:9000: Failed to connect to remote host: Connection refused"
        debug_error_string = "UNKNOWN:failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:9000: Failed to connect to remote host: Connection refused {grpc_status:14, created_time:"2023-09-02T04:35:38.320601475+00:00"}"
```

**Comment by gfmota** [comment]
Can you show your docker-compose file? There may be a problem in services connection

**Comment by Barathwaja** [comment]
Hi @gfmota,

I fixed the issue.

1 - had to reinstall to docker to fix "host" network.
2 - client fails when server is not running. It would be nice to implement retry mechanism when client is unreachable. In addition to that the message thrown is misleading to actual problem faced, it would be nice to show different error message when client is unreachable instead of refused.

**Comment by danieljanes** [comment]
@Barathwaja @gfmota we're going to switch to a completely new communication stack soon. The new stack, based on a the gRPC request-response model, comes with much better error handling, retries, and much more.

Closing this issue for now.
