### ISSUE TITLE
Module Not Found Error When Using Ray Along With Flower On W11 #40046

### ISSUE THREAD

**Issue by psklavos1** [adap/flower#2453]
### Describe the bug

When trying to run Ray along with Flower the Ray clients initialized Pop a Module Not Found Error for the non-main modules. If I transfer all the functionality on one module there seems to be no issue, but it is impossible to use different modules.

OS== W11
ray==2.6.3
python==3.11.5
tensorflow==2.13.0
flwr== 1.5.0

![image](https://github.com/adap/flower/assets/74099479/0f237e88-ed54-4344-9035-7cdb91b4a0be)

### Steps/Code to Reproduce

[sim.zip](https://github.com/adap/flower/files/12794695/sim.zip)
If you copy paste the code from client module to the sim.py the problem is fixed

### Expected Results

If run with all the classes implemented in same module, Ray is working perfectly, However if you try using more than 1 classes, ray seems to recognise only the one containing the main, The rest pop a module Not Found Error

### Actual Results
```
INFO flwr 2023-10-03 19:25:57,690 | app.py:175 | Starting Flower simulation, config: ServerConfig(num_rounds=10, round_timeout=None)
2023-10-03 19:26:04,735 INFO worker.py:1621 -- Started a local Ray instance.
INFO flwr 2023-10-03 19:26:06,928 | app.py:210 | Flower VCE: Ray initialized with resources: {'object_store_memory': 2400243302.0, 'memory': 4800486606.0, 'node:127.0.0.1': 1.0, 'node:__internal_head__': 1.0, 'CPU': 12.0, 'GPU': 1.0}
INFO flwr 2023-10-03 19:26:06,929 | app.py:224 | Flower VCE: Resources for each Virtual Client: {'num_cpus': 1, 'num_gpus': 0.0}
INFO flwr 2023-10-03 19:26:06,952 | app.py:270 | Flower VCE: Creating VirtualClientEngineActorPool with 12 actors
INFO flwr 2023-10-03 19:26:06,952 | server.py:89 | Initializing global parameters
INFO flwr 2023-10-03 19:26:06,953 | server.py:276 | Requesting initial parameters from one random client
ERROR flwr 2023-10-03 19:26:17,013 | ray_client_proxy.py:147 | Traceback (most recent call last):
  File "C:\Users\Sklavos17\miniconda3\envs\flower\Lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 140, in _submit_job
    res = self.actor_pool.get_client_result(self.cid, timeout)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sklavos17\miniconda3\envs\flower\Lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 402, in get_client_result
    return self._fetch_future_result(cid)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sklavos17\miniconda3\envs\flower\Lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 288, in _fetch_future_result
    res_cid, res = ray.get(future)  # type: (str, ClientRes)
                   ^^^^^^^^^^^^^^^
  File "C:\Users\Sklavos17\miniconda3\envs\flower\Lib\site-packages\ray\_private\auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sklavos17\miniconda3\envs\flower\Lib\site-packages\ray\_private\client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sklavos17\miniconda3\envs\flower\Lib\site-packages\ray\_private\worker.py", line 2524, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError: ray::DefaultActor.run() (pid=24288, ip=127.0.0.1, actor_id=1eadf90127672f9baeccf43601000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x000001E76FC0D5D0>)
  File "python\ray\_raylet.pyx", line 1370, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1404, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 753, in ray._raylet.raise_if_dependency_failed
ray.exceptions.RaySystemError: System error: No module named 'client'
traceback: Traceback (most recent call last):
  File "C:\Users\Sklavos17\miniconda3\envs\flower\Lib\site-packages\ray\_private\serialization.py", line 387, in deserialize_objects
    obj = self._deserialize_object(data, metadata, object_ref)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sklavos17\miniconda3\envs\flower\Lib\site-packages\ray\_private\serialization.py", line 268, in _deserialize_object
    return self._deserialize_msgpack_data(data, metadata_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sklavos17\miniconda3\envs\flower\Lib\site-packages\ray\_private\serialization.py", line 223, in _deserialize_msgpack_data
    python_objects = self._deserialize_pickle5_data(pickle5_data)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sklavos17\miniconda3\envs\flower\Lib\site-packages\ray\_private\serialization.py", line 211, in _deserialize_pickle5_data
    obj = pickle.loads(in_band, buffers=buffers)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'client'

ERROR flwr 2023-10-03 19:26:17,018 | ray_client_proxy.py:148 | ray::DefaultActor.run() (pid=24288, ip=127.0.0.1, actor_id=1eadf90127672f9baeccf43601000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x000001E76FC0D5D0>)
  File "python\ray\_raylet.pyx", line 1370, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1404, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 753, in ray._raylet.raise_if_dependency_failed
ray.exceptions.RaySystemError: System error: No module named 'client'
traceback: Traceback (most recent call last):
  File "C:\Users\Sklavos17\miniconda3\envs\flower\Lib\site-packages\ray\_private\serialization.py", line 387, in deserialize_objects
    obj = self._deserialize_object(data, metadata, object_ref)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sklavos17\miniconda3\envs\flower\Lib\site-packages\ray\_private\serialization.py", line 268, in _deserialize_object
    return self._deserialize_msgpack_data(data, metadata_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sklavos17\miniconda3\envs\flower\Lib\site-packages\ray\_private\serialization.py", line 223, in _deserialize_msgpack_data
    python_objects = self._deserialize_pickle5_data(pickle5_data)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sklavos17\miniconda3\envs\flower\Lib\site-packages\ray\_private\serialization.py", line 211, in _deserialize_pickle5_data
    obj = pickle.loads(in_band, buffers=buffers)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'client'
ERROR flwr 2023-10-03 19:26:17,020 | app.py:294 | ray::DefaultActor.run() (pid=24288, ip=127.0.0.1, actor_id=1eadf90127672f9baeccf43601000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x000001E76FC0D5D0>)
  File "python\ray\_raylet.pyx", line 1370, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1404, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 753, in ray._raylet.raise_if_dependency_failed
ray.exceptions.RaySystemError: System error: No module named 'client'
traceback: Traceback (most recent call last):
  File "C:\Users\Sklavos17\miniconda3\envs\flower\Lib\site-packages\ray\_private\serialization.py", line 387, in deserialize_objects
    obj = self._deserialize_object(data, metadata, object_ref)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sklavos17\miniconda3\envs\flower\Lib\site-packages\ray\_private\serialization.py", line 268, in _deserialize_object
    return self._deserialize_msgpack_data(data, metadata_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(DefaultActor pid=24288)           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(DefaultActor pid=24288)   File "C:\Users\Sklavos17\miniconda3\envs\flower\Lib\site-packages\ray\_private\serialization.py", line 268, in _deserialize_object   
(DefaultActor pid=24288)     return self._deserialize_msgpack_data(data, metadata_fields)
(DefaultActor pid=24288)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(DefaultActor pid=24288)   File "C:\Users\Sklavos17\miniconda3\envs\flower\Lib\site-packages\ray\_private\serialization.py", line 223, in _deserialize_msgpack_data
(DefaultActor pid=24288)     python_objects = self._deserialize_pickle5_data(pickle5_data)
(DefaultActor pid=24288)                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(DefaultActor pid=24288)   File "C:\Users\Sklavos17\miniconda3\envs\flower\Lib\site-packages\ray\_private\serialization.py", line 211, in _deserialize_pickle5_data
(DefaultActor pid=24288)     obj = pickle.loads(in_band, buffers=buffers)(DefaultActor pid=24288)           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(DefaultActor pid=24288) ModuleNotFoundError: No module named 'client'
```

**Comment by jafermarq** [comment]
Hi @psklavos1, i just ran your `sim.py` directly and it seems to work fine.

**Comment by psklavos1** [comment]
Would you mind passing me some information about your setup(OS, and
versions for ray etc). At the moment I think the problem can be attributed
to my Os but it is something i can solve without using a VM.
Your help is greatly appreciated

**Comment by psklavos1** [comment]
Everything seems to work fine. 
Thank you

**Comment by jafermarq** [comment]
So it worked fine on WSL?

**Comment by psklavos1** [comment]
It worked for the restricted edition problem I sent. I still have the same issue in a bigger test,  yet I assume the problem was solved as the smaller problem was solved. I am just looking to find what is that makes the 2 projects different with the one working and the other crashing
