### ISSUE TITLE
Android example application closing by itself during federated training execution.

### ISSUE THREAD

**Issue by rmouram** [adap/flower#2460]
### Describe the bug

The android example application closing by itself during federated training execution. There doesn't need to be anything specific occurring, it just closes. It is preventing experiments from being carried out. This problem occurs using the apk available in the android java example, and using android studio.

APK: android 12 SKQ1.210908.001, smartphone xiaomi MIUI Global 14.0.3.
Androi Studio Giraffe 2023.3.1.20-windows.... SO intalled in virtual device: Android 11.

Logcat panel for emulator exemple:

-------- beginning of crash
2023-10-05 11:06:14.608 6656-6656 AndroidRuntime flwr.android_client D Shutting down VM
2023-10-05 11:06:14.618 6656-6656 AndroidRuntime flwr.android_client E FATAL EXCEPTION: main
Process: flwr.android_client, PID: 6656
java.lang.IndexOutOfBoundsException: offset(88) should be less than line limit(49)
at android.text.TextLine.measure(TextLine.java:353)
at android.text.Layout.getHorizontal(Layout.java:1213)
at android.text.Layout.getHorizontal(Layout.java:1190)
at android.text.Layout.getPrimaryHorizontal(Layout.java:1160)
at android.widget.TextView.bringPointIntoView(TextView.java:9861)
at android.widget.TextView.onPreDraw(TextView.java:7562)
at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1093)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3089)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1952)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8171)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)
at android.view.Choreographer.doCallbacks(Choreographer.java:796)
at android.view.Choreographer.doFrame(Choreographer.java:731)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:223)
at android.app.ActivityThread.main(ActivityThread.java:7656)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
2023-10-05 11:06:14.736 6656-6656 Process flwr.android_client I Sending signal. PID: 6656 SIG: 9

### Steps/Code to Reproduce

It is not necessary

### Expected Results

The application does not close by itself

### Actual Results

The application is closing by itself

**Comment by WilliamLindskog** [comment]
Hi @rmouram 

Thanks for raising this. Are you still experiencing this issue?

**Comment by WilliamLindskog** [comment]
Hi @rmouram 

Thanks for raising this. Are you still experiencing this issue?

**Comment by WilliamLindskog** [comment]
Closing this as it seems to have been solved in newer versions.
