### ISSUE TITLE
(Example) XGBoost Comprehensive - Run in flwr simulation 

### ISSUE THREAD

**Issue by WilliamLindskog** [adap/flower#2638]
### Describe the bug

Hi there, 
When setting up a client function that is being called for the `flwr["simulation"]` package, as below
```python
# Define Flower client
class XgbClient(fl.client.Client):
    def __init__(
            self, 
            fds: FederatedDataset, 
            device: str, 
            cid: str, 
            cfg: DictConfig
        ) -> None:
        self.config = None
        self.fds = fds
        self.device = device
        self.cid = int(cid)
        self.cfg = cfg
        self.params = BST_PARAMS[cfg.dataset_name]
        self.bst = None

        # Load data
        self.train_dmatrix, self.test_dmatrix = self._load_data()
        self.num_train = self.train_dmatrix.num_row()
        self.num_test = self.test_dmatrix.num_row()
        self.num_local_round = self.cfg.num_local_round

    def get_parameters(self, ins: GetParametersIns) -> GetParametersRes:
        _ = (self, ins)
        return GetParametersRes(
            status=Status(code=Code.OK,message="OK",),
            parameters=Parameters(tensor_type="", tensors=[]),
        )

    def _local_boost(self):
        # Update trees based on local training data.
        for i in range(self.num_local_round):
            self.bst.update(self.train_dmatrix, self.bst.num_boosted_rounds())

        # Extract the last N=num_local_round trees for sever aggregation
        bst = self.bst[
            self.bst.num_boosted_rounds()
            - self.num_local_round : self.bst.num_boosted_rounds()
        ]

        return bst
    def fit(self, ins: FitIns) -> FitRes:
        if not self.bst:
            # First round local training
            log(INFO, "Start training at round 1")
            bst = xgb.train(
                self.params,
                self.train_dmatrix,
                num_boost_round=self.num_local_round,
                evals=[(self.test_dmatrix, "test"), (self.train_dmatrix, "train")],
            )
            self.config = self.bst.save_config()
            self.bst = bst
        else:
            for item in ins.parameters.tensors:
                global_model = bytearray(item)

            # Load global model into booster
            self.bst.load_model(global_model)
            self.bst.load_config(self.config)

            bst = self._local_boost()

        local_model = bst.save_raw("json")
        local_model_bytes = bytes(local_model)

        # Save model in tmp folder
        bst.save_model(f"./treesXnets/tmp/{self.cid}.txt")

        return FitRes(
            status=Status(
                code=Code.OK,
                message="OK",
            ),
            parameters=Parameters(tensor_type="", tensors=[local_model_bytes]),
            num_examples=self.num_train,
            metrics={},
        )

    def evaluate(self, ins: EvaluateIns) -> EvaluateRes:
        # Load local model into booster
        #self.bst = xgb.Booster(self.params)
        #self.bst.load_model(f"./treesXnets/tmp/{self.cid}.txt")

        eval_results = self.bst.eval_set(
            evals=[(self.test_dmatrix, "test")],
            iteration=self.bst.num_boosted_rounds() - 1,
        )

        metric = round(float(eval_results.split("\t")[1].split(":")[1]), 4)

        global_round = ins.config["global_round"]
        if self.params["eval_metric"] == 'auc':
            metric_name = "AUC"
        elif self.params["eval_metric"] == 'rmse':
            metric_name = "RMSE"
        log(INFO, f"{metric_name} = {metric} at round {global_round}")

        return EvaluateRes(
            status=Status(
                code=Code.OK,
                message="OK",
            ),
            loss=0.0,
            num_examples=self.num_test,
            metrics={f"{metric_name}": metric},
        )

    def _load_data(self,) -> Tuple[DataLoader, DataLoader]:
        """Return the dataloader for the client."""
        # Get client partition
        partition = self.fds.load_partition(self.cid, split="train")

        # Divide partition into train and test
        partition_train_test = partition.train_test_split(test_size=0.2)
        trainset, testset = partition_train_test["train"], partition_train_test["test"]
        dataset_name = self.cfg.dataset_name

        # Set train and test data
        train_data, test_data = DataFrame(trainset), DataFrame(testset)
        X_train, y_train = train_data.drop(TARGET[dataset_name], axis=1), train_data[TARGET[dataset_name]]
        X_test, y_test = test_data.drop(TARGET[dataset_name], axis=1), test_data[TARGET[dataset_name]]

        # Set DMatrix
        train_dmatrix = xgb.DMatrix(X_train, label=y_train)
        valid_dmatrix = xgb.DMatrix(X_test, label=y_test)

        return train_dmatrix, valid_dmatrix
```
there is no self.bst to be found in the evaluate function (the `_load_data` function is not so important here). Is this because of _stateful_ clients? Or is there something I can change in the code? If it is because of stateful clients, how can I get around this?

### Steps/Code to Reproduce

First clone my `experimental` branch using following command: 
```bash
git clone -b experimental https://github.com/WilliamLindskog/flower.git
```

The following commands will let you run the main script that calls XgbClient from the file `client.py`. The code follows the baseline structure. 

```bash
#  cd into treesXnets
cd baselines/treesXnets/

python -m treesXnets.main
```

### Expected Results

The expected result is that self.bst can be called in the evaluate function in `client.py` in class `XgbClient`, since it is being initiated in fit function and should be reachable in the same class. 

### Actual Results

This is the error message: 
`ERROR flwr 2023-11-27 13:43:28,341 | ray_client_proxy.py:145 | Traceback (most recent call last):
  File "/home/dnde/.cache/pypoetry/virtualenvs/treesxnets-cAOkYJQP-py3.10/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 138, in _submit_job
    res = self.actor_pool.get_client_result(self.cid, timeout)
  File "/home/dnde/.cache/pypoetry/virtualenvs/treesxnets-cAOkYJQP-py3.10/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 414, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/dnde/.cache/pypoetry/virtualenvs/treesxnets-cAOkYJQP-py3.10/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 300, in _fetch_future_result
    res_cid, res = ray.get(future)  # type: (str, ClientRes)
  File "/home/dnde/.cache/pypoetry/virtualenvs/treesxnets-cAOkYJQP-py3.10/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/dnde/.cache/pypoetry/virtualenvs/treesxnets-cAOkYJQP-py3.10/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/dnde/.cache/pypoetry/virtualenvs/treesxnets-cAOkYJQP-py3.10/lib/python3.10/site-packages/ray/_private/worker.py", line 2524, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientException): ray::DefaultActor.run() (pid=75737, ip=192.168.201.105, actor_id=a0a0b956cb36cffb584460a201000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f6b34466fe0>)
  File "/home/dnde/.cache/pypoetry/virtualenvs/treesxnets-cAOkYJQP-py3.10/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 209, in evaluate
    return maybe_call_evaluate(
  File "/home/dnde/.cache/pypoetry/virtualenvs/treesxnets-cAOkYJQP-py3.10/lib/python3.10/site-packages/flwr/client/client.py", line 243, in maybe_call_evaluate
    return client.evaluate(evaluate_ins)
  File "/home/dnde/Documents/flower/baselines/treesXnets/treesXnets/client.py", line 188, in evaluate
    eval_results = self.bst.eval_set(
AttributeError: 'NoneType' object has no attribute 'eval_set'`

**Comment by WilliamLindskog** [comment]
Nevermind, I realized that my `server.py` script was wrong. Now, it is working. 

We can close this issue, sorry for the inconvenience.

**Comment by mxrcx** [comment]
Hey @WilliamLindskog do you remember what was wrong with your server.py script, or what changes you made to make it work? I ran into the exact same problem...
Thank you!

**Comment by fabiankay** [comment]
Hi @mxrcx 

I experienced the same problem and was able to solve it using the following code in my Clients' evaluate function

```
def evaluate(self, ins: EvaluateIns) -> EvaluateRes:
        bst = xgb.Booster(params=params)
        for para in ins.parameters.tensors:
            para_b = bytearray(para)
        ## log(INFO, para_b)
        # Load global model
        bst.load_model(para_b)

        eval_results = bst.eval_set(
            evals=[(self.valid_dmatrix, "valid")],
            iteration=bst.num_boosted_rounds() - 1,
        )
        auc = round(float(eval_results.split("\t")[1].split(":")[1]), 4)

        global_round = ins.config["global_round"]
        log(INFO, f"AUC = {auc} at round {global_round}")

        return EvaluateRes(
            status=Status(
                code=Code.OK,
                message="OK",
            ),
            loss=0.0,
            num_examples=self.num_test,
            metrics={"AUC": auc},
        )
```

Instead of accessing the self.bst model which is not available since it has never been initialized at evaluation, the code above sets up a new Booster based on the parameters revieved from the server.
It's basically the same as on server-side evaluation.

However, I have not yet double checked this solution - happy to hear what you think.
Does this may solve the issue?
