### ISSUE TITLE
When i try to execute an example i get an error examples/dp-sgd-mnist

### ISSUE THREAD

**Issue by zJaska** [adap/flower#2702]
### Describe the bug

poetry run python3 server.py, i do this command and i get:

2023-12-09 13:59:21.294897: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
INFO flwr 2023-12-09 13:59:23,718 | app.py:163 | Starting Flower server, config: ServerConfig(num_rounds=1, round_timeout=None)
INFO flwr 2023-12-09 13:59:23,751 | app.py:176 | Flower ECE: gRPC server running (1 rounds), SSL is disabled
INFO flwr 2023-12-09 13:59:23,755 | server.py:89 | Initializing global parameters
INFO flwr 2023-12-09 13:59:23,768 | server.py:272 | Using initial parameters provided by strategy
INFO flwr 2023-12-09 13:59:23,769 | server.py:91 | Evaluating initial parameters
Traceback (most recent call last):
  File "server.py", line 56, in <module>
    main(args)
  File "server.py", line 43, in main
    fl.server.start_server(
  File "/home/jaskaran/.cache/pypoetry/virtualenvs/dp-sgd-mnist-K_ZTmSVa-py3.8/lib/python3.8/site-packages/flwr/server/app.py", line 184, in start_server
    hist = run_fl(
  File "/home/jaskaran/.cache/pypoetry/virtualenvs/dp-sgd-mnist-K_ZTmSVa-py3.8/lib/python3.8/site-packages/flwr/server/app.py", line 225, in run_fl
    hist = server.fit(num_rounds=config.num_rounds, timeout=config.round_timeout)
  File "/home/jaskaran/.cache/pypoetry/virtualenvs/dp-sgd-mnist-K_ZTmSVa-py3.8/lib/python3.8/site-packages/flwr/server/server.py", line 92, in fit
    res = self.strategy.evaluate(0, parameters=self.parameters)
  File "/home/jaskaran/.cache/pypoetry/virtualenvs/dp-sgd-mnist-K_ZTmSVa-py3.8/lib/python3.8/site-packages/flwr/server/strategy/fedavg.py", line 163, in evaluate
    eval_res = self.evaluate_fn(server_round, parameters_ndarrays, {})
TypeError: evaluate() takes 1 positional argument but 3 were given

### Steps/Code to Reproduce

fl.server.start_server(
        server_address="0.0.0.0:8080",
        config=fl.server.ServerConfig(num_rounds=args.num_rounds),
        strategy=strategy
    )

### Expected Results

I should be able to start the server

### Actual Results

I get the error

**Comment by WilliamLindskog** [comment]
Hi @zJaska, 

Thanks for raising this. Are you still experiencing this issue?

**Comment by WilliamLindskog** [comment]
Hi, 

I am closing this issue as in the new DP example we have moved away from previous flwr versions. I tested the new example and it runs.
