### ISSUE TITLE
[quickstart-pytorch] Produces a typeError in flower_datasets in client.py

### ISSUE THREAD

**Issue by neogismm** [adap/flower#2711]
### Describe the bug

I'm new to flower and wanted to try out the quickstart-pytorch example. It requires the flower_datasets library in the client.py file and running it produces a typeError:

```
python client.py
Traceback (most recent call last):
  File "client.py", line 109, in <module>
    trainloader, testloader = load_data(node_id=node_id)
  File "client.py", line 75, in load_data
    partition = fds.load_partition(node_id)
  File "/Users/neog/Desktop/FL-blockchain/.venv/lib/python3.8/site-packages/flwr_datasets/federated_dataset.py", line 139, in load_partition
    return partitioner.load_partition(node_id)
  File "/Users/neog/Desktop/FL-blockchain/.venv/lib/python3.8/site-packages/flwr_datasets/partitioner/iid_partitioner.py", line 50, in load_partition
    return self.dataset.shard(
  File "/Users/neog/Desktop/FL-blockchain/.venv/lib/python3.8/site-packages/datasets/arrow_dataset.py", line 4591, in shard
    if not 0 <= index < num_shards:
TypeError: '<=' not supported between instances of 'int' and 'NoneType'
```

### Steps/Code to Reproduce

python client.py

### Expected Results

successful run

### Actual Results

typeError

**Comment by jafermarq** [comment]
Hi @neogismm , did you pass the `--node-id` argument to your client? Like this:
```
python3 client.py --node-id 0 # or any integer in {0,1,2}
```

**Comment by neogismm** [comment]
Actually, I did not. It works fine now with the node-id argument.
Thanks @jafermarq

**Comment by jafermarq** [comment]
@neogismm , would you like to create a small PR to make the `node-id` as a required argument to argparse?

**Comment by neogismm** [comment]
Yeah, I can definitely try. Thanks for the suggestion.
