### ISSUE TITLE
 RayActorClientProxy.get_parameters() missing 1 required positional argument: 'group_id'

### ISSUE THREAD

**Issue by HM64MS** [adap/flower#3277]
### What is your question?

Hi everyone when I run the code this error raises and I don't have any idea what is wrong with the code. anyone can help?
INFO:flwr:Requesting initial parameters from one random client
ERROR :     RayActorClientProxy.get_parameters() missing 1 required positional argument: 'group_id'
ERROR:flwr:RayActorClientProxy.get_parameters() missing 1 required positional argument: 'group_id'
ERROR :     Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flwr/simulation/app.py", line 308, in start_simulation
    hist = run_fl(
  File "/usr/local/lib/python3.10/dist-packages/flwr/server/server.py", line 483, in run_fl
    hist, elapsed_time = server.fit(
  File "<ipython-input-18-714026ed2a0a>", line 22, in fit
    self.parameters = self._get_initial_parameters(timeout=timeout)
  File "<ipython-input-18-714026ed2a0a>", line 208, in _get_initial_parameters
    get_parameters_res_tree = random_client.get_parameters(ins=ins, timeout=timeout)
TypeError: RayActorClientProxy.get_parameters() missing 1 required positional argument: 'group_id'

ERROR:flwr:Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flwr/simulation/app.py", line 308, in start_simulation
    hist = run_fl(
  File "/usr/local/lib/python3.10/dist-packages/flwr/server/server.py", line 483, in run_fl
    hist, elapsed_time = server.fit(
  File "<ipython-input-18-714026ed2a0a>", line 22, in fit
    self.parameters = self._get_initial_parameters(timeout=timeout)
  File "<ipython-input-18-714026ed2a0a>", line 208, in _get_initial_parameters
    get_parameters_res_tree = random_client.get_parameters(ins=ins, timeout=timeout)
TypeError: RayActorClientProxy.get_parameters() missing 1 required positional argument: 'group_id'

**Comment by Chinothebuilder** [comment]
I am having similar issues. Has there been any solution or a way around this issue?

**Comment by WilliamLindskog** [comment]
Hi @HM64MS 

Thanks for raising this. Could you provide what example/code you are running?

**Comment by WilliamLindskog** [comment]
This seems to have to do with version mismatch between `flwr` and `ray`. Did you find a solution?

**Comment by Chinothebuilder** [comment]
At the time I couldn’t find a way around this. Please, has there been a
solution?

**Comment by WilliamLindskog** [comment]
what example are you running?

**Comment by WilliamLindskog** [comment]
Is this still not working? @Chinothebuilder @HM64MS

**Comment by WilliamLindskog** [comment]
Closing this as this seems to have been a mismatch between `ray` and `flwr` which has been resolved in newer version.
