### ISSUE TITLE
Unable to load saved model  using SaveModelStrategy

### ISSUE THREAD

**Issue by 0x59d** [adap/flower#3616]
### Describe the bug

I'm unable to load the model when using the SaveModelStrategy in [the docs](https://flower.ai/docs/framework/how-to-save-and-load-model-checkpoints.html). 

The .npz files get created during training but when attempting to use the latest round file with torch.load it throws the following RunTimeError: 

> RuntimeError: [enforce fail at inline_container.cc:129] . file in archive is not in a subdirectory: arr_0.npy

Below is the trace and logging files returned

> List of files:  ['./round-1-weights.npz', './round-2-weights.npz']
> Loading pre-trained model from:  ./round-2-weights.npz
> Error executing job with overrides: []
> Traceback (most recent call last):
>   File "main.py", line 39, in main
>     state_dict = torch.load(latest_round_file)
>   File "/home/nitty/miniconda3/envs/flower-tutorial/lib/python3.8/site-packages/torch/serialization.py", line 777, in load
>     with _open_zipfile_reader(opened_file) as opened_zipfile:
>   File "/home/nitty/miniconda3/envs/flower-tutorial/lib/python3.8/site-packages/torch/serialization.py", line 282, in __init__
>     super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))

### Steps/Code to Reproduce

Following the docs [here](https://flower.ai/docs/framework/how-to-save-and-load-model-checkpoints.html)

Model loaded with:

`net = Net(cfg.num_classes)`

Using MNIST dataset (instead of net = cifar.Net().to(DEVICE))

Listing files in the docs had an error that was changed to using the correct file names:

~~list_of_files = [fname for fname in glob.glob("./model_round_*")]~~
list_of_files = [fname for fname in glob.glob("./round-*")]

### Expected Results

To load the model without errors

### Actual Results

Following RunTimeError observed:

> RuntimeError: [enforce fail at inline_container.cc:129] . file in archive is not in a subdirectory: arr_0.npy

**Comment by 0x59d** [comment]
Nevermind, seems like I have to use the np load method to access npz files. Doh!
