### ISSUE TITLE
KeyError: 'partition-id' when running Flower App

### ISSUE THREAD

**Issue by berryfanta** [adap/flower#4120]
### Describe the bug

Hi Flower Team! I am trying to run the Flower App and am running into the following error when starting the Client Apps:
```
$ flower-supernode ./ --insecure
INFO :      Starting Flower SuperNode
WARNING :   Option `--insecure` was set. Starting insecure HTTP client connected to 0.0.0.0:9092.
INFO :      
INFO :      [RUN 4100797107668583610, ROUND 1]
INFO :      Received: train message 605cd65a-b561-411f-80ef-1ecc29fc59a9
ERROR :     ClientApp raised an exception
Traceback (most recent call last):
  File "~/miniconda3/envs/app-pytorch/lib/python3.9/site-packages/flwr/client/app.py", line 526, in start_client_internal
    reply_message = client_app(message=message, context=context)
  File "~/miniconda3/envs/app-pytorch/lib/python3.9/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "~/miniconda3/envs/app-pytorch/lib/python3.9/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "~/miniconda3/envs/app-pytorch/lib/python3.9/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "~/github/flower/app-pytorch/app_pytorch/client_app.py", line 46, in client_fn
    partition_id = context.node_config["partition-id"]
KeyError: 'partition-id'
```
The `flower client app` and `flower client server` were created using `flwr new` and following the system prompts to create and install a pytorch flower app

This is the resulting `pyproject.toml`
```
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "app-pytorch"
version = "1.0.0"
description = ""
license = "Apache-2.0"
dependencies = [
    "flwr[simulation]>=1.10.0",
    "flwr-datasets[vision]>=0.3.0",
    "torch==2.2.1",
    "torchvision==0.17.1",
]

[tool.hatch.build.targets.wheel]
packages = ["."]

[tool.flwr.app]
publisher = "berryfanta"

[tool.flwr.app.components]
serverapp = "app_pytorch.server_app:app"
clientapp = "app_pytorch.client_app:app"

[tool.flwr.app.config]
num-server-rounds = 3
fraction-fit = 0.5
local-epochs = 1

[tool.flwr.federations]
default = "local-simulation"

[tool.flwr.federations.local-simulation]
options.num-supernodes = 2
```

Here is my `pip list`
```
$ pip list
Package                   Version     Editable project location
------------------------- ----------- ------------------------------------
aiohappyeyeballs          2.4.0
aiohttp                   3.10.5
aiosignal                 1.3.1
app-pytorch               1.0.0       ~github/flower/app-pytorch
async-timeout             4.0.3
attrs                     24.2.0
certifi                   2024.8.30
cffi                      1.17.0
charset-normalizer        3.3.2
click                     8.1.7
colorama                  0.4.6
contourpy                 1.3.0
cryptography              42.0.8
cycler                    0.12.1
datasets                  2.19.2
dill                      0.3.8
filelock                  3.15.4
flwr                      1.11.0
flwr-datasets             0.3.0
fonttools                 4.53.1
frozenlist                1.4.1
fsspec                    2024.3.1
grpcio                    1.66.1
huggingface-hub           0.24.6
idna                      3.8
importlib_resources       6.4.4
iterators                 0.0.2
Jinja2                    3.1.4
jsonschema                4.23.0
jsonschema-specifications 2023.12.1
kiwisolver                1.4.5
markdown-it-py            3.0.0
MarkupSafe                2.1.5
matplotlib                3.9.2
mdurl                     0.1.2
mpmath                    1.3.0
msgpack                   1.0.8
multidict                 6.0.5
multiprocess              0.70.16
networkx                  3.2.1
numpy                     1.26.4
nvidia-cublas-cu12        12.1.3.1
nvidia-cuda-cupti-cu12    12.1.105
nvidia-cuda-nvrtc-cu12    12.1.105
nvidia-cuda-runtime-cu12  12.1.105
nvidia-cudnn-cu12         8.9.2.26
nvidia-cufft-cu12         11.0.2.54
nvidia-curand-cu12        10.3.2.106
nvidia-cusolver-cu12      11.4.5.107
nvidia-cusparse-cu12      12.1.0.106
nvidia-nccl-cu12          2.19.3
nvidia-nvjitlink-cu12     12.6.68
nvidia-nvtx-cu12          12.1.105
packaging                 24.1
pandas                    2.2.2
pathspec                  0.12.1
pillow                    10.4.0
pip                       24.2
protobuf                  4.25.4
pyarrow                   16.1.0
pyarrow-hotfix            0.6
pycparser                 2.22
pycryptodome              3.20.0
Pygments                  2.18.0
pyparsing                 3.1.4
python-dateutil           2.9.0.post0
pytz                      2024.1
PyYAML                    6.0.2
ray                       2.10.0
referencing               0.35.1
requests                  2.32.3
rich                      13.8.0
rpds-py                   0.20.0
seaborn                   0.13.2
setuptools                72.1.0
shellingham               1.5.4
six                       1.16.0
sympy                     1.13.2
tomli                     2.0.1
tomli_w                   1.0.0
torch                     2.2.1
torchvision               0.17.1
tqdm                      4.66.5
triton                    2.2.0
typer                     0.9.4
typing_extensions         4.12.2
tzdata                    2024.1
urllib3                   2.2.2
wheel                     0.43.0
xxhash                    3.5.0
yarl                      1.9.6
zipp                      3.20.1
```
Thank you!

-Barry

### Steps/Code to Reproduce

To reproduce:
1. `pip install flower[simulation]`
2. `flwr new` (follow system prompts to create pytorch app)
In terminal 1
4. `flower-superlink --insecure`
In terminal 2
5. `flower-server-app <path_to_pyproject.toml> --insecure`
In terminal 3
4. `flower-supernode <path_to_pyproject.toml> --insecure`
In terminal 4
4. `flower-supernode <path_to_pyproject.toml> --insecure`

### Expected Results

Run should execute without issue. It seems that the `--superlink` is started as expected and accepting messages from the `supernode`
```
$ flower-superlink --insecure 
INFO :      Starting Flower SuperLink
WARNING :   Option `--insecure` was set. Starting insecure HTTP server.
INFO :      Flower ECE: Starting Driver API (gRPC-rere) on 0.0.0.0:9091
INFO :      Flower ECE: Starting Fleet API (gRPC-rere) on 0.0.0.0:9092
INFO :      [Fleet.CreateNode] Request ping_interval=30.0
INFO :      [Fleet.CreateNode] Created node_id=-6869784751205817255
INFO :      [Fleet.PullTaskIns] node_id=-6869784751205817255
```
And the server-app initializes the experiment correctly:
```
$ flower-server-app ./ --insecure
WARNING :   Option `--insecure` was set. Starting insecure HTTP client connected to 0.0.0.0:9091.
INFO :      Starting Flower ServerApp, config: num_rounds=3, no round_timeout
INFO :      
INFO :      [INIT]
INFO :      Using initial global parameters provided by strategy
INFO :      Starting evaluation of initial global parameters
INFO :      Evaluation returned no results (`None`)
INFO :      
INFO :      [ROUND 1]
```

### Actual Results

(Full stack trace above)
```
$ flower-supernode ./ --insecure
INFO :      Starting Flower SuperNode
WARNING :   Option `--insecure` was set. Starting insecure HTTP client connected to 0.0.0.0:9092.
INFO :      
INFO :      [RUN 4100797107668583610, ROUND 1]
INFO :      Received: train message 196e9fa5-62bc-4a75-a653-338e6e3e6f25
ERROR :     ClientApp raised an exception
...
File "~/github/flower/app-pytorch/app_pytorch/client_app.py", line 46, in client_fn
    partition_id = context.node_config["partition-id"]
KeyError: 'partition-id'
```

**Comment by jafermarq** [comment]
Hi @berryfanta , the Flower projects created via `flwr new` make use of [Flower Datasets]() to facilitate the partitioning of the data. When you run the project in simulation (as is the default in `flwr run`) the `partition-id` and the total number of partitions are set automatically. The latter is read from the `num-partitions` in the `pyproject.toml`.

If you want to run the same `ClientApp` as part of a `SuperNode`, you need to start the latter by providing such `num-partitions` and `partition-id` values (since thye are expected in the code generated via `flwr new`). You can do so like this:

```shell
flower-supernode --node-config "num-partitions=10 partition-id=2"
```

I hope this helps!! 

As you can see in many of our `quickstart-examples` (for example in [examples/quickstart-pytorch](https://github.com/adap/flower/tree/main/examples/quickstart-pytorch#run-with-the-deployment-engine)) (see the note left at the end) we are soon going to provide an easy mechanism to run all of them using the deployment components: `SuperNode`, `SuperLink` and `SuperExec`. This will be done via a convenient `docker-compose` file. So stay tuned!

**Comment by berryfanta** [comment]
@jafermarq I see, Thank you!
