### ISSUE TITLE
Mypy complains it cannot find numpy after `poetry update`

### ISSUE THREAD

**Issue by pedropgusmao** [adap/flower#597]
Hello,

I ran `poetry update` and got the follwing:
```
Updating dependencies
Resolving dependencies... (42.5s)

Writing lock file

Package operations: 0 installs, 4 updates, 1 removal

  • Removing numpy-stubs (0.0.1 f3c6315)
  • Updating importlib-metadata (3.3.0 -> 3.4.0)
  • Updating pygments (2.7.3 -> 2.7.4)
  • Updating grpcio (1.34.0 -> 1.32.0)
  • Updating numpy (1.18.5 -> 1.19.5)
```

I believe `numpy-stubs` are still needed as now I get the following error after running `dev/fnt.sh` 
```
Format code and run all test scripts
Fixing /home/pedro/repos/flower/src/py/flwr_example/pytorch_save_weights/client.py
Skipped 1 files
=== test.sh ===
- clang-format: done
Skipped 1 files
- isort:  done
All done! ✨ 🍰 ✨
59 files would be left unchanged.
- black:  done
- docformatter:  done
Traceback (most recent call last):
  File "/home/pedro/.pyenv/versions/3.7.9/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/pedro/.pyenv/versions/3.7.9/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/pedro/.pyenv/versions/flower-3.7.9/lib/python3.7/site-packages/mypy/__main__.py", line 12, in <module>
    main(None, sys.stdout, sys.stderr)
  File "mypy/main.py", line 90, in main
  File "mypy/build.py", line 180, in build
  File "mypy/build.py", line 254, in _build
  File "mypy/build.py", line 2630, in dispatch
  File "mypy/build.py", line 2946, in process_graph
  File "mypy/build.py", line 3024, in process_fresh_modules
  File "mypy/build.py", line 1958, in fix_cross_refs
  File "mypy/fixup.py", line 25, in fixup_module
  File "mypy/fixup.py", line 89, in visit_symbol_table
  File "mypy/fixup.py", line 45, in visit_type_info
  File "mypy/fixup.py", line 91, in visit_symbol_table
  File "mypy/nodes.py", line 767, in accept
  File "mypy/fixup.py", line 115, in visit_decorator
  File "mypy/nodes.py", line 677, in accept
  File "mypy/fixup.py", line 99, in visit_func_def
  File "mypy/types.py", line 1098, in accept
  File "mypy/fixup.py", line 184, in visit_callable_type
  File "mypy/types.py", line 1724, in accept
  File "mypy/fixup.py", line 251, in visit_union_type
  File "mypy/types.py", line 794, in accept
  File "mypy/fixup.py", line 160, in visit_instance
  File "mypy/types.py", line 794, in accept
  File "mypy/fixup.py", line 153, in visit_instance
  File "mypy/fixup.py", line 262, in lookup_qualified_typeinfo
  File "mypy/fixup.py", line 290, in lookup_qualified
  File "mypy/fixup.py", line 299, in lookup_qualified_stnode
  File "mypy/lookup.py", line 29, in lookup_fully_qualified
AssertionError: Cannot find module for numpy.ndarray
```

**Comment by pedropgusmao** [comment]
Creating a new repo and installing from scratch solves the issue.

**Comment by danieljanes** [comment]
Ok, let me know if this solves the issue. Sometimes it helps to delete the entire venv and install from it from scratch.

If you want to use the helper scripts in `dev`:

```bash
./dev/venv-delete.sh
./dev/rm-caches.sh
rm poetry.lock
./dev/venv-create.sh
./dev/bootstrap.sh
```

**Comment by danieljanes** [comment]
Btw, there's a PR (soon to be merged) that updates many dev dependencies (#590).

**Comment by danieljanes** [comment]
#590 was merged yesterday. Is this still an issues @pedropgusmao ?

**Comment by danieljanes** [comment]
> Creating a new repo and installing from scratch solves the issue.

Oh sorry I guess I misread that comment, closing this issue now.
