### ISSUE TITLE
Advanced Tensorflow example using GPU

### ISSUE THREAD

**Issue by fanto88** [adap/flower#831]
Like the title suggest, i would like to try using GPU instead of CPU for the training session of the Advanced_tensorflow project inside the example of flower.

The problem is that i get this error doing so:

```
INFO flower 2021-09-04 01:25:48,299 | server.py:123 | initial parameters (loss, other metrics): 2.3025829792022705, {'accuracy': 0.09700000286102295}
INFO flower 2021-09-04 01:25:48,301 | server.py:133 | FL starting
DEBUG flower 2021-09-04 01:25:48,301 | server.py:251 | fit_round: strategy sampled 3 clients (out of 10)
DEBUG flower 2021-09-04 01:25:48,925 | connection.py:68 | Insecure gRPC channel closed
Traceback (most recent call last):
  File "D:\Davide\Uni\TesiMagistrale\Esempi\Advanced_example\client.py", line 107, in <module>
    main()
  File "D:\Davide\Uni\TesiMagistrale\Esempi\Advanced_example\client.py", line 90, in main
    fl.client.start_numpy_client("127.0.0.1:5050", client=client)
  File "D:\Davide\Uni\TesiMagistrale\Esempi\Advanced_example\venv\lib\site-packages\flwr\client\app.py", line 112, in start_numpy_client
    start_client(
  File "D:\Davide\Uni\TesiMagistrale\Esempi\Advanced_example\venv\lib\site-packages\flwr\client\app.py", line 65, in start_client
    client_message, sleep_duration, keep_going = handle(
  File "D:\Davide\Uni\TesiMagistrale\Esempi\Advanced_example\venv\lib\site-packages\flwr\client\grpc_client\message_handler.py", line 40, in handle
    return _fit(client, server_msg.fit_ins), 0, True
  File "D:\Davide\Uni\TesiMagistrale\Esempi\Advanced_example\venv\lib\site-packages\flwr\client\grpc_client\message_handler.py", line 57, in _fit
    fit_res = client.fit(fit_ins)
  File "D:\Davide\Uni\TesiMagistrale\Esempi\Advanced_example\venv\lib\site-packages\flwr\client\numpy_client.py", line 179, in fit
    results = self.numpy_client.fit(parameters, ins.config)
  File "D:\Davide\Uni\TesiMagistrale\Esempi\Advanced_example\client.py", line 39, in fit
    history = self.model.fit(
  File "D:\Davide\Uni\TesiMagistrale\Esempi\Advanced_example\venv\lib\site-packages\keras\engine\training.py", line 1134, in fit
    data_handler = data_adapter.get_data_handler(
  File "D:\Davide\Uni\TesiMagistrale\Esempi\Advanced_example\venv\lib\site-packages\keras\engine\data_adapter.py", line 1383, in get_data_handler
DEBUG flower 2021-09-04 01:25:48,938 | connection.py:68 | Insecure gRPC channel closed
Traceback (most recent call last):
  File "D:\Davide\Uni\TesiMagistrale\Esempi\Advanced_example\client.py", line 107, in <module>
    main()
  File "D:\Davide\Uni\TesiMagistrale\Esempi\Advanced_example\client.py", line 90, in main
    fl.client.start_numpy_client("127.0.0.1:5050", client=client)
  File "D:\Davide\Uni\TesiMagistrale\Esempi\Advanced_example\venv\lib\site-packages\flwr\client\app.py", line 112, in start_numpy_client
    start_client(
  File "D:\Davide\Uni\TesiMagistrale\Esempi\Advanced_example\venv\lib\site-packages\flwr\client\app.py", line 65, in start_client
    client_message, sleep_duration, keep_going = handle(
  File "D:\Davide\Uni\TesiMagistrale\Esempi\Advanced_example\venv\lib\site-packages\flwr\client\grpc_client\message_handler.py", line 40, in handle
    return _fit(client, server_msg.fit_ins), 0, True
  File "D:\Davide\Uni\TesiMagistrale\Esempi\Advanced_example\venv\lib\site-packages\flwr\client\grpc_client\message_handler.py", line 57, in _fit
    fit_res = client.fit(fit_ins)
  File "D:\Davide\Uni\TesiMagistrale\Esempi\Advanced_example\venv\lib\site-packages\flwr\client\numpy_client.py", line 179, in fit
    results = self.numpy_client.fit(parameters, ins.config)
  File "D:\Davide\Uni\TesiMagistrale\Esempi\Advanced_example\client.py", line 39, in fit
    history = self.model.fit(
  File "D:\Davide\Uni\TesiMagistrale\Esempi\Advanced_example\venv\lib\site-packages\keras\engine\training.py", line 1134, in fit
    data_handler = data_adapter.get_data_handler(
  File "D:\Davide\Uni\TesiMagistrale\Esempi\Advanced_example\venv\lib\site-packages\keras\engine\data_adapter.py", line 1383, in get_data_handler
    return DataHandler(*args, **kwargs)
    return DataHandler(*args, **kwargs)
  File "D:\Davide\Uni\TesiMagistrale\Esempi\Advanced_example\venv\lib\site-packages\keras\engine\data_adapter.py", line 1138, in __init__
  File "D:\Davide\Uni\TesiMagistrale\Esempi\Advanced_example\venv\lib\site-packages\keras\engine\data_adapter.py", line 1138, in __init__
    self._adapter = adapter_cls(
  File "D:\Davide\Uni\TesiMagistrale\Esempi\Advanced_example\venv\lib\site-packages\keras\engine\data_adapter.py", line 322, in __init__
    self._adapter = adapter_cls(
  File "D:\Davide\Uni\TesiMagistrale\Esempi\Advanced_example\venv\lib\site-packages\keras\engine\data_adapter.py", line 322, in __init__
    dataset = self.slice_inputs(indices_dataset, inputs)
  File "D:\Davide\Uni\TesiMagistrale\Esempi\Advanced_example\venv\lib\site-packages\keras\engine\data_adapter.py", line 348, in slice_inputs
    dataset = self.slice_inputs(indices_dataset, inputs)
  File "D:\Davide\Uni\TesiMagistrale\Esempi\Advanced_example\venv\lib\site-packages\keras\engine\data_adapter.py", line 348, in slice_inputs
    tf.data.Dataset.from_tensors(inputs).repeat()
  File "D:\Davide\Uni\TesiMagistrale\Esempi\Advanced_example\venv\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 606, in from_tensors
    tf.data.Dataset.from_tensors(inputs).repeat()
  File "D:\Davide\Uni\TesiMagistrale\Esempi\Advanced_example\venv\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 606, in from_tensors
    return TensorDataset(tensors)
  File "D:\Davide\Uni\TesiMagistrale\Esempi\Advanced_example\venv\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 3829, in __init__
    return TensorDataset(tensors)
  File "D:\Davide\Uni\TesiMagistrale\Esempi\Advanced_example\venv\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 3829, in __init__
    variant_tensor = gen_dataset_ops.tensor_dataset(
    variant_tensor = gen_dataset_ops.tensor_dataset(
  File "D:\Davide\Uni\TesiMagistrale\Esempi\Advanced_example\venv\lib\site-packages\tensorflow\python\ops\gen_dataset_ops.py", line 7043, in tensor_dataset
  File "D:\Davide\Uni\TesiMagistrale\Esempi\Advanced_example\venv\lib\site-packages\tensorflow\python\ops\gen_dataset_ops.py", line 7043, in tensor_dataset
    _ops.raise_from_not_ok_status(e, name)
  File "D:\Davide\Uni\TesiMagistrale\Esempi\Advanced_example\venv\lib\site-packages\tensorflow\python\framework\ops.py", line 6941, in raise_from_not_ok_status
    _ops.raise_from_not_ok_status(e, name)
  File "D:\Davide\Uni\TesiMagistrale\Esempi\Advanced_example\venv\lib\site-packages\tensorflow\python\framework\ops.py", line 6941, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InternalError: Failed copying input tensor from /job:localhost/replica:0/task:0/device:GPU:0 to /job:localhost/replica:0/task:0/device:CPU:0 in order to run TensorDataset: Dst tensor is not initialized. [Op:TensorDataset]
tensorflow.python.framework.errors_impl.InternalError: Failed copying input tensor from /job:localhost/replica:0/task:0/device:GPU:0 to /job:localhost/replica:0/task:0/device:CPU:0 in order to run TensorDataset: Dst tensor is not initialized. [Op:TensorDataset]
```

How can i fix it?

I have a radeon 3060 ti, tensorflow can see the GPU and use it with no problem. The code is like the example, i just added those lines:

```
physical_devices = tf.config.experimental.list_physical_devices('GPU')
if len(physical_devices) > 0:
    tf.config.experimental.set_memory_growth(physical_devices[0], True)
```

Inside client.py and server.py to see if i could fix the memory allocation error, but didn't work.

**Comment by krille90** [comment]
It seems you are running out of GPU memory.

Did you try a lower batch_size? Alternatively, try to run fewer clients and see if that fixes your issue.

**Comment by zhanggyarcher** [comment]
Hello @fanto88 , how did you solve this?
