### ISSUE TITLE
Raspberry pi 3 cannot import flwr

### ISSUE THREAD

**Issue by JozefKondas** [adap/flower#904]
I installed flower : 

`pip install flwr`

It installed properly and now I have problem to import it. Thanks for help 

`Python 3.9.2 (default, Mar 12 2021, 04:06:34) 
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import flwr
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/Desktop/flower/flower_env/lib/python3.9/site-packages/flwr/__init__.py", line 18, in <module>
    from . import client, server, simulation
  File "/home/pi/Desktop/flower/flower_env/lib/python3.9/site-packages/flwr/client/__init__.py", line 18, in <module>
    from .app import start_client as start_client
  File "/home/pi/Desktop/flower/flower_env/lib/python3.9/site-packages/flwr/client/app.py", line 25, in <module>
    from .grpc_client.connection import insecure_grpc_connection
  File "/home/pi/Desktop/flower/flower_env/lib/python3.9/site-packages/flwr/client/grpc_client/connection.py", line 22, in <module>
    import grpc
  File "/home/pi/Desktop/flower/flower_env/lib/python3.9/site-packages/grpc/__init__.py", line 22, in <module>
    from grpc import _compression
  File "/home/pi/Desktop/flower/flower_env/lib/python3.9/site-packages/grpc/_compression.py", line 15, in <module>
    from grpc._cython import cygrpc
ImportError: /home/pi/Desktop/flower/flower_env/lib/python3.9/site-packages/grpc/_cython/cygrpc.cpython-39-arm-linux-gnueabihf.so: undefined symbol: __atomic_exchange_8
Python 3.9.2 (default, Mar 12 2021, 04:06:34) 
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import flwr
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/Desktop/flower/flower_env/lib/python3.9/site-packages/flwr/__init__.py", line 18, in <module>
    from . import client, server, simulation
  File "/home/pi/Desktop/flower/flower_env/lib/python3.9/site-packages/flwr/client/__init__.py", line 18, in <module>
    from .app import start_client as start_client
  File "/home/pi/Desktop/flower/flower_env/lib/python3.9/site-packages/flwr/client/app.py", line 25, in <module>
    from .grpc_client.connection import insecure_grpc_connection
  File "/home/pi/Desktop/flower/flower_env/lib/python3.9/site-packages/flwr/client/grpc_client/connection.py", line 22, in <module>
    import grpc
  File "/home/pi/Desktop/flower/flower_env/lib/python3.9/site-packages/grpc/__init__.py", line 22, in <module>
    from grpc import _compression
  File "/home/pi/Desktop/flower/flower_env/lib/python3.9/site-packages/grpc/_compression.py", line 15, in <module>
    from grpc._cython import cygrpc
ImportError: /home/pi/Desktop/flower/flower_env/lib/python3.9/site-packages/grpc/_cython/cygrpc.cpython-39-arm-linux-gnueabihf.so: undefined symbol: __atomic_exchange_8
`

**Comment by tanertopal** [comment]
@JozefKondas could you provide a bit more information on the system? Which OS, Version, which RPI, etc. Also would be nice if you can copy the error message into a comment or edit it into your description.

**Comment by JozefKondas** [comment]
`PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
`

**Comment by jafermarq** [comment]
@JozefKondas, have you tried running the [Embedded Devices](https://github.com/adap/flower/tree/main/examples/embedded_devices) example? There are several packages that require native compilation for `aarch64` (i.e. RPi, Jetson, and other devices running Arm CPUs).  It this [`Dockerfile`](https://github.com/adap/flower/blob/main/examples/embedded_devices/base_images/cpu/Dockerfile) you can see the steps I followed to make everything work. It can take a little while to install. I believe you can run those commands individually on the terminal (i.e. outside a Docker setting). let me know how it goes!

**Comment by JozefKondas** [comment]
I downloaded ubuntu image instead of Rapsbian and It's working
