### ISSUE TITLE
Error when running Flower

### ISSUE THREAD

**Issue by AnasKhann22** [adap/flower#931]
Hi, I'm new to Flower and Federated Learning. I have created a below server file using Flower and whenever I'm running it I'm getting below error. I'm using mac M1 2020.  Can someone please help me with this. 

`import flwr as fl
import sys
import numpy as np

class SaveModelStrategy(fl.server.strategy.FedAvg):
    def aggregate_fit(
        self,
        rnd,
        results,
        failures
    ):
        aggregated_weights = super().aggregate_fit(rnd, results, failures)
        if aggregated_weights is not None:
            # Save aggregated_weights
            print(f"Saving round {rnd} aggregated_weights...")
            np.savez(f"round-{rnd}-weights.npz", *aggregated_weights)
        return aggregated_weights

# Create strategy and run server
strategy = SaveModelStrategy()

# Start Flower server for three rounds of federated learning
fl.server.start_server(
        server_address = 'localhost:'+str(sys.argv[1]) ,
        config={"num_rounds": 2} ,
        grpc_max_message_length = 1024*1024*1024,
        strategy = strategy
)`

`(python38) anaskhan@ANAS-MBP pythonFLimages % python server.py 5002                    
Traceback (most recent call last):
  File "server.py", line 1, in <module>
    import flwr as fl
  File "/Users/anaskhan/miniforge3/envs/python38/lib/python3.8/site-packages/flwr/__init__.py", line 18, in <module>
    from . import client, server, simulation
  File "/Users/anaskhan/miniforge3/envs/python38/lib/python3.8/site-packages/flwr/client/__init__.py", line 18, in <module>
    from .app import start_client as start_client
  File "/Users/anaskhan/miniforge3/envs/python38/lib/python3.8/site-packages/flwr/client/app.py", line 25, in <module>
    from .grpc_client.connection import insecure_grpc_connection
  File "/Users/anaskhan/miniforge3/envs/python38/lib/python3.8/site-packages/flwr/client/grpc_client/connection.py", line 22, in <module>
    import grpc
  File "/Users/anaskhan/miniforge3/envs/python38/lib/python3.8/site-packages/grpc/__init__.py", line 22, in <module>
    from grpc import _compression
  File "/Users/anaskhan/miniforge3/envs/python38/lib/python3.8/site-packages/grpc/_compression.py", line 15, in <module>
    from grpc._cython import cygrpc
ImportError: dlopen(/Users/anaskhan/miniforge3/envs/python38/lib/python3.8/site-packages/grpc/_cython/cygrpc.cpython-38-darwin.so, 0x0002): symbol not found in flat namespace '_CFRelease'`

**Comment by iReivax1** [comment]
im running into the same issue

**Comment by jafermarq** [comment]
Have you looked into this? (see final comment) https://github.com/grpc/grpc/issues/25082
