### ISSUE TITLE
Issue with flower quickstart

### ISSUE THREAD

**Issue by VincentMag** [adap/flower#998]
Hello,
I was trying to run the quickstart tensorflow example, however whenever I launch client.py, I get the following error, did anyone run into the same issue ?  

Files already downloaded and verified
Files already downloaded and verified
DEBUG flower 2022-01-07 07:36:28,587 | connection.py:36 | ChannelConnectivity.IDLE
INFO flower 2022-01-07 07:36:28,587 | app.py:61 | Opened (insecure) gRPC connection
DEBUG flower 2022-01-07 07:36:28,587 | connection.py:36 | ChannelConnectivity.CONNECTING
DEBUG flower 2022-01-07 07:36:28,587 | connection.py:68 | Insecure gRPC channel closed
Traceback (most recent call last):
  File "client.py", line 141, in <module>
    fl.client.start_numpy_client("[::]:5040", client=CifarClient())
  File "C:\anaconda\lib\site-packages\flwr\client\app.py", line 112, in start_numpy_client
    start_client(
  File "C:\anaconda\lib\site-packages\flwr\client\app.py", line 64, in start_client
    server_message = receive()
  File "C:\anaconda\lib\site-packages\flwr\client\grpc_client\connection.py", line 60, in <lambda>
    receive: Callable[[], ServerMessage] = lambda: next(server_message_iterator)
  File "C:\anaconda\lib\site-packages\grpc\_channel.py", line 426, in __next__
    return self._next()
  File "C:\anaconda\lib\site-packages\grpc\_channel.py", line 826, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "failed to connect to all addresses"
        debug_error_string = "{"created":"@1641537388.595000000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3159,"referenced_errors":[{"created":"@1641537388.595000000","description":"failed to connect to all addresses","file":"src/core/lib/transport/error_utils.cc","file_line":147,"grpc_status":14}]}"
>

Thanks in advance

**Comment by tanertopal** [comment]
@VincentMag is your issue resolved?

**Comment by loukas371** [comment]
> You should revise your start_numpy_client() credentials. In my case replacing the IP to localhost worked (same error message): fl.client.start_numpy_client("localhost:8080", client=Client())

worked for me and I had the same error running the pytorch example

**Comment by WrynnChou** [comment]
> localhost:8080
Thanks，it works.
